### ISSUE TITLE
Providing the feature to extract an Arrow::Array into two NArray arrays.

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/red-arrow-numo-narray#1]
An Arrow::Array consists of two arrays. One is the value array, and the other is the null bitmap.

I want to provide the feature to extract these arrays as NArray arrays in red-arrow-numo-narray.

By simply consideration, `Arrow::Array#to_narray` is a candidate of the name of such the feature.  But this feature returns two arrays.  I worry about if `to_XXX` method is appropriate name for extraction.

What do you think about the name and the function of such the feature?

**Comment by kou** [comment]
I agree with the feature.

Do you know how does NArray handle null? Just not supported?

If it's not supported, how about raising an error when an `Arrow::Array` has one or more nulls?

```ruby
class Arrow::Array
  def to_narray
    unless n_nulls.zero?
      raise UnconvertableError, "can't convert #{self.class} that has null values to NArray"
    end
    narray = value_data_type.narray_class.new(length)
    narray.store_binary(buffer.data.to_s)
    narray
  end  
end
```

**Comment by mrkn** [comment]
As far as I know, NArray doesn't have features to manage null bitmap.

Raising error for arrays with nulls looks good starting point for me.

**Comment by kou** [comment]
Implemented.

**Comment by mrkn** [comment]
Thanks a lot!
