### ISSUE TITLE
error on conversion from arrow to numo

### ISSUE THREAD

**Issue by dsisnero** [red-data-tools/red-arrow-numo-narray#5]
```text
C:\Users\Dominic E Sisneros\source\repos\ruby\gists>cat numo_to_array.rb
require 'numo/narray'
require 'arrow-numo-narray'
a = Numo::Int32.new(3,100000000).seq
table_a = a.to_arrow
a_t = table_a.to_narray
 b = a * 3
 b2 = a_t * 3

puts a_t
puts b2
```

```text
ruby numo_to_array.rb 1> output.txt 2>&1
```

C:\Users\Dominic E Sisneros\source\repos\ruby\gists>ruby numo_to_array.rb 1> output.txt 2>&1
[output.txt](https://github.com/red-data-tools/red-arrow-numo-narray/files/4670049/output.txt)

**Comment by dsisnero** [comment]
https://gist.github.com/dsisnero/58a53fc4c796e4c64bea45955e74b4ca

**Comment by kou** [comment]
Thanks for your report.
I've fixed this.
